package com.mycompany.proyectofinal;

import CapaNegocio.EmployeeServices;
import Entidades.Employee;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author luiscelano
 */
public class EmployeesForm extends javax.swing.JFrame {

    /**
     * Creates new form EmployeesForm
     */
    public EmployeesForm() {
        initComponents();
        EmployeeServices services = new EmployeeServices();
        jTable1.setModel(services.fetchEmployees());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genders = new javax.swing.ButtonGroup();
        maritalStatus = new javax.swing.ButtonGroup();
        jpTableMenu = new javax.swing.JPopupMenu();
        opUpdate = new javax.swing.JMenuItem();
        opDelete = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnames = new javax.swing.JTextField();
        txtlastnames = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        rdsingle = new javax.swing.JRadioButton();
        rdmarried = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rdmale = new javax.swing.JRadioButton();
        rdfemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCreate1 = new javax.swing.JButton();

        opUpdate.setText("Editar");
        opUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opUpdateActionPerformed(evt);
            }
        });
        jpTableMenu.add(opUpdate);

        opDelete.setText("Eliminar");
        opDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDeleteActionPerformed(evt);
            }
        });
        jpTableMenu.add(opDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 53, 53));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Estado Civil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txtcedula.setBackground(new java.awt.Color(80, 80, 80));
        txtcedula.setForeground(java.awt.Color.white);
        txtcedula.setToolTipText("");
        txtcedula.setBorder(null);
        txtcedula.setCaretColor(java.awt.Color.white);
        txtcedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtcedula.setMargin(new java.awt.Insets(0, 5, 0, 0));
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 280, 40));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtnames.setBackground(new java.awt.Color(80, 80, 80));
        txtnames.setForeground(java.awt.Color.white);
        txtnames.setToolTipText("");
        txtnames.setBorder(null);
        txtnames.setCaretColor(java.awt.Color.white);
        txtnames.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtnames.setMargin(new java.awt.Insets(0, 5, 0, 0));
        getContentPane().add(txtnames, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 280, 40));

        txtlastnames.setBackground(new java.awt.Color(80, 80, 80));
        txtlastnames.setForeground(java.awt.Color.white);
        txtlastnames.setToolTipText("");
        txtlastnames.setBorder(null);
        txtlastnames.setCaretColor(java.awt.Color.white);
        txtlastnames.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtlastnames.setMargin(new java.awt.Insets(0, 5, 0, 0));
        getContentPane().add(txtlastnames, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 280, 40));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Cédula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Agregar Empleado");

        button1.setLabel("button1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 80));

        maritalStatus.add(rdsingle);
        rdsingle.setForeground(java.awt.Color.white);
        rdsingle.setText("Soltero");
        getContentPane().add(rdsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        maritalStatus.add(rdmarried);
        rdmarried.setForeground(java.awt.Color.white);
        rdmarried.setText("Casado");
        getContentPane().add(rdmarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Género");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        genders.add(rdmale);
        rdmale.setForeground(java.awt.Color.white);
        rdmale.setText("Masculino");
        getContentPane().add(rdmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        genders.add(rdfemale);
        rdfemale.setForeground(java.awt.Color.white);
        rdfemale.setText("Femenino");
        getContentPane().add(rdfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Edad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        txtage.setBackground(new java.awt.Color(80, 80, 80));
        txtage.setForeground(java.awt.Color.white);
        txtage.setToolTipText("");
        txtage.setBorder(null);
        txtage.setCaretColor(java.awt.Color.white);
        txtage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtage.setMargin(new java.awt.Insets(0, 5, 0, 0));
        getContentPane().add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 280, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Cedula", "Estado Civil", "Genero", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jpTableMenu);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 710, 420));

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCreate.setText("Agregar Registro");
        btnCreate.setBorder(null);
        btnCreate.setBorderPainted(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 210, 40));

        jPanel1.setBackground(new java.awt.Color(56, 56, 56));

        btnCreate1.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCreate1.setText("Limpiar");
        btnCreate1.setBorder(null);
        btnCreate1.setBorderPainted(false);
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addComponent(btnCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(btnCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1160, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        EmployeeServices services = new EmployeeServices();
        Employee empleado = new Employee();
        empleado.setNames(txtnames.getText());
        empleado.setLastnames(txtlastnames.getText());
        empleado.setCedula(Long.parseLong(txtcedula.getText()));
        
        if(rdmarried.isSelected()) {
            empleado.setMaritalStatus("Casado");
        } else if(rdsingle.isSelected()){
            empleado.setMaritalStatus("Soltero");
        }
        
        if(rdmale.isSelected()) {
            empleado.setGender("Masculino");
        } else if(rdfemale.isSelected()) {
            empleado.setGender("Femenino");
        }
        empleado.setAge(Integer.parseInt(txtage.getText()));
        
        services.CreateEmployee(empleado);
        jTable1.setModel(services.fetchEmployees());
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void opUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opUpdateActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
       Vector<Object> rowData = tm.getDataVector().elementAt(jTable1.getSelectedRow());
       Employee empleado = new Employee();
       EmployeeServices services = new EmployeeServices();
       
       empleado.setLineAsObject(rowData);
        
        services.EditEmployee(empleado);
        jTable1.setModel(services.fetchEmployees());
    }//GEN-LAST:event_opUpdateActionPerformed

    private void opDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
       Vector<Object> rowData = tm.getDataVector().elementAt(jTable1.getSelectedRow());
       Employee empleado = new Employee();
       EmployeeServices services = new EmployeeServices();
       
       empleado.setLineAsObject(rowData);
        
        services.DeleteEmployee(empleado);
        jTable1.setModel(services.fetchEmployees());
    }//GEN-LAST:event_opDeleteActionPerformed

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        // TODO add your handling code here:
        txtnames.setText("");
        txtlastnames.setText("");
        txtcedula.setText("");
        txtage.setText("");
        genders.clearSelection();
        maritalStatus.clearSelection();
    }//GEN-LAST:event_btnCreate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreate1;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup genders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPopupMenu jpTableMenu;
    private javax.swing.ButtonGroup maritalStatus;
    private javax.swing.JMenuItem opDelete;
    private javax.swing.JMenuItem opUpdate;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton rdfemale;
    private javax.swing.JRadioButton rdmale;
    private javax.swing.JRadioButton rdmarried;
    private javax.swing.JRadioButton rdsingle;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtlastnames;
    private javax.swing.JTextField txtnames;
    // End of variables declaration//GEN-END:variables
}
